# CMake generated Testfile for 
# Source directory: /root/pomaieco/pomaidb
# Build directory: /root/pomaieco/pomaidb/build_debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[crc32c_test]=] "/root/pomaieco/pomaidb/build_debug/crc32c_test")
set_tests_properties([=[crc32c_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;148;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[memtable_test]=] "/root/pomaieco/pomaidb/build_debug/memtable_test")
set_tests_properties([=[memtable_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;152;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[mailbox_test]=] "/root/pomaieco/pomaidb/build_debug/mailbox_test")
set_tests_properties([=[mailbox_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;156;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[wal_test]=] "/root/pomaieco/pomaidb/build_debug/wal_test")
set_tests_properties([=[wal_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;160;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[segment_test]=] "/root/pomaieco/pomaidb/build_debug/segment_test")
set_tests_properties([=[segment_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;164;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[shard_manifest_test]=] "/root/pomaieco/pomaidb/build_debug/shard_manifest_test")
set_tests_properties([=[shard_manifest_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;168;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[oracle_test]=] "/root/pomaieco/pomaidb/build_debug/oracle_test")
set_tests_properties([=[oracle_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;172;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[recall_test]=] "/root/pomaieco/pomaidb/build_debug/recall_test")
set_tests_properties([=[recall_test]=] PROPERTIES  LABELS "recall" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;176;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_basic_test]=] "/root/pomaieco/pomaidb/build_debug/db_basic_test")
set_tests_properties([=[db_basic_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;181;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_batch_test]=] "/root/pomaieco/pomaidb/build_debug/db_batch_test")
set_tests_properties([=[db_batch_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;185;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_persistence_test]=] "/root/pomaieco/pomaidb/build_debug/db_persistence_test")
set_tests_properties([=[db_persistence_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;189;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_segment_test]=] "/root/pomaieco/pomaidb/build_debug/db_segment_test")
set_tests_properties([=[db_segment_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;193;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_open_test]=] "/root/pomaieco/pomaidb/build_debug/db_open_test")
set_tests_properties([=[db_open_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;197;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_consistency_test]=] "/root/pomaieco/pomaidb/build_debug/db_consistency_test")
set_tests_properties([=[db_consistency_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;201;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_partial_search_test]=] "/root/pomaieco/pomaidb/build_debug/db_partial_search_test")
set_tests_properties([=[db_partial_search_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;205;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[manifest_test]=] "/root/pomaieco/pomaidb/build_debug/manifest_test")
set_tests_properties([=[manifest_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;209;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[membrane_test]=] "/root/pomaieco/pomaidb/build_debug/membrane_test")
set_tests_properties([=[membrane_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;213;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[membrane_persistence_test]=] "/root/pomaieco/pomaidb/build_debug/membrane_persistence_test")
set_tests_properties([=[membrane_persistence_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;217;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[shard_concurrency_test]=] "/root/pomaieco/pomaidb/build_debug/shard_concurrency_test")
set_tests_properties([=[shard_concurrency_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;221;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[iterator_test]=] "/root/pomaieco/pomaidb/build_debug/iterator_test")
set_tests_properties([=[iterator_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;225;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[metadata_test]=] "/root/pomaieco/pomaidb/build_debug/metadata_test")
set_tests_properties([=[metadata_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;229;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[search_filter_test]=] "/root/pomaieco/pomaidb/build_debug/search_filter_test")
set_tests_properties([=[search_filter_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;233;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[manifest_corruption_test]=] "/root/pomaieco/pomaidb/build_debug/manifest_corruption_test")
set_tests_properties([=[manifest_corruption_test]=] PROPERTIES  LABELS "crash" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;237;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[recovery_test]=] "/root/pomaieco/pomaidb/build_debug/recovery_test")
set_tests_properties([=[recovery_test]=] PROPERTIES  LABELS "crash" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;241;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[pomai_crash_replay]=] "/root/pomaieco/pomaidb/build_debug/pomai_crash_test")
set_tests_properties([=[pomai_crash_replay]=] PROPERTIES  LABELS "crash" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;264;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_concurrency_tsan_test]=] "/root/pomaieco/pomaidb/build_debug/db_concurrency_tsan_test")
set_tests_properties([=[db_concurrency_tsan_test]=] PROPERTIES  LABELS "tsan" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;271;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[shard_runtime_tsan_test]=] "/root/pomaieco/pomaidb/build_debug/shard_runtime_tsan_test")
set_tests_properties([=[shard_runtime_tsan_test]=] PROPERTIES  LABELS "tsan" _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;141;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;275;pomai_add_labeled_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[c_api_test]=] "/root/pomaieco/pomaidb/build_debug/c_api_test")
set_tests_properties([=[c_api_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/root/pomaieco/pomaidb/CMakeLists.txt;322;add_test;/root/pomaieco/pomaidb/CMakeLists.txt;0;")
