# CMake generated Testfile for 
# Source directory: /home/autocookie/pomaieco/pomaidb
# Build directory: /home/autocookie/pomaieco/pomaidb/build2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[crc32c_test]=] "/home/autocookie/pomaieco/pomaidb/build2/crc32c_test")
set_tests_properties([=[crc32c_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;267;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[hnsw_pomaidb_test]=] "/home/autocookie/pomaieco/pomaidb/build2/hnsw_pomaidb_test")
set_tests_properties([=[hnsw_pomaidb_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;271;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[memtable_test]=] "/home/autocookie/pomaieco/pomaidb/build2/memtable_test")
set_tests_properties([=[memtable_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;275;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[mailbox_test]=] "/home/autocookie/pomaieco/pomaidb/build2/mailbox_test")
set_tests_properties([=[mailbox_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;279;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[logging_test]=] "/home/autocookie/pomaieco/pomaidb/build2/logging_test")
set_tests_properties([=[logging_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;283;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[wal_test]=] "/home/autocookie/pomaieco/pomaidb/build2/wal_test")
set_tests_properties([=[wal_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;287;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[segment_test]=] "/home/autocookie/pomaieco/pomaidb/build2/segment_test")
set_tests_properties([=[segment_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;291;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[fp16_test]=] "/home/autocookie/pomaieco/pomaidb/build2/fp16_test")
set_tests_properties([=[fp16_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;295;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[shard_manifest_test]=] "/home/autocookie/pomaieco/pomaidb/build2/shard_manifest_test")
set_tests_properties([=[shard_manifest_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;299;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[oracle_test]=] "/home/autocookie/pomaieco/pomaidb/build2/oracle_test")
set_tests_properties([=[oracle_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;303;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[routing_table_test]=] "/home/autocookie/pomaieco/pomaidb/build2/routing_table_test")
set_tests_properties([=[routing_table_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;307;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[streaming_index_test]=] "/home/autocookie/pomaieco/pomaidb/build2/streaming_index_test")
set_tests_properties([=[streaming_index_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;311;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[recall_test]=] "/home/autocookie/pomaieco/pomaidb/build2/recall_test")
set_tests_properties([=[recall_test]=] PROPERTIES  LABELS "recall" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;315;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_basic_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_basic_test")
set_tests_properties([=[db_basic_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;320;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_batch_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_batch_test")
set_tests_properties([=[db_batch_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;324;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_persistence_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_persistence_test")
set_tests_properties([=[db_persistence_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;328;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_segment_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_segment_test")
set_tests_properties([=[db_segment_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;332;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_open_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_open_test")
set_tests_properties([=[db_open_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;336;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_consistency_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_consistency_test")
set_tests_properties([=[db_consistency_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;340;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_partial_search_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_partial_search_test")
set_tests_properties([=[db_partial_search_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;344;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[routing_engine_test]=] "/home/autocookie/pomaieco/pomaidb/build2/routing_engine_test")
set_tests_properties([=[routing_engine_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;348;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[manifest_test]=] "/home/autocookie/pomaieco/pomaidb/build2/manifest_test")
set_tests_properties([=[manifest_test]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;352;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[membrane_test]=] "/home/autocookie/pomaieco/pomaidb/build2/membrane_test")
set_tests_properties([=[membrane_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;356;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[membrane_persistence_test]=] "/home/autocookie/pomaieco/pomaidb/build2/membrane_persistence_test")
set_tests_properties([=[membrane_persistence_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;360;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[shard_concurrency_test]=] "/home/autocookie/pomaieco/pomaidb/build2/shard_concurrency_test")
set_tests_properties([=[shard_concurrency_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;364;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[iterator_test]=] "/home/autocookie/pomaieco/pomaidb/build2/iterator_test")
set_tests_properties([=[iterator_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;368;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[metadata_test]=] "/home/autocookie/pomaieco/pomaidb/build2/metadata_test")
set_tests_properties([=[metadata_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;372;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[search_filter_test]=] "/home/autocookie/pomaieco/pomaidb/build2/search_filter_test")
set_tests_properties([=[search_filter_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;376;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[rag_contract_test]=] "/home/autocookie/pomaieco/pomaidb/build2/rag_contract_test")
set_tests_properties([=[rag_contract_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;380;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[rag_search_test]=] "/home/autocookie/pomaieco/pomaidb/build2/rag_search_test")
set_tests_properties([=[rag_search_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;384;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[search_newest_wins_test]=] "/home/autocookie/pomaieco/pomaidb/build2/search_newest_wins_test")
set_tests_properties([=[search_newest_wins_test]=] PROPERTIES  LABELS "integ" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;388;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[manifest_corruption_test]=] "/home/autocookie/pomaieco/pomaidb/build2/manifest_corruption_test")
set_tests_properties([=[manifest_corruption_test]=] PROPERTIES  LABELS "crash" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;392;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[recovery_test]=] "/home/autocookie/pomaieco/pomaidb/build2/recovery_test")
set_tests_properties([=[recovery_test]=] PROPERTIES  LABELS "crash" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;396;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[pomai_crash_replay]=] "/home/autocookie/pomaieco/pomaidb/build2/pomai_crash_test")
set_tests_properties([=[pomai_crash_replay]=] PROPERTIES  LABELS "crash" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;423;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[db_concurrency_tsan_test]=] "/home/autocookie/pomaieco/pomaidb/build2/db_concurrency_tsan_test")
set_tests_properties([=[db_concurrency_tsan_test]=] PROPERTIES  LABELS "tsan" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;430;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[shard_runtime_tsan_test]=] "/home/autocookie/pomaieco/pomaidb/build2/shard_runtime_tsan_test")
set_tests_properties([=[shard_runtime_tsan_test]=] PROPERTIES  LABELS "tsan" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;434;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[basic_workload_tsan_test]=] "/home/autocookie/pomaieco/pomaidb/build2/basic_workload_tsan_test")
set_tests_properties([=[basic_workload_tsan_test]=] PROPERTIES  LABELS "tsan" _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;260;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;438;pomai_add_labeled_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
add_test([=[c_api_test]=] "/home/autocookie/pomaieco/pomaidb/build2/c_api_test")
set_tests_properties([=[c_api_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;512;add_test;/home/autocookie/pomaieco/pomaidb/CMakeLists.txt;0;")
subdirs("tests/fuzz")
